config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks", :registrations => "users/registrations", :confirmations => "users/confirmations"}

  root 'home#index'
  get 'welcome' , to: 'home#welcome' #サンプルプレイリスト
  get 'samplelist' , to: 'home#samplelist' #サンプルプレイリスト
  # get 'name_check', to: 'home#name_check'#ユーザー名重複チェック用
  get 'chart' , to: 'home#chart' #チャート
  get 'about' , to: 'home#about' #プレイリストについて
  get 'privacy' , to: 'home#privacy' #個人情報保護
  get 'term' , to: 'home#term' #利用規約
  get 'tokutei' , to: 'home#tokutei' #特定商取引に関する表記
  #著作権どうするか
  # get 'copyright' , to: 'home#copyright'

  # get 'auto_complete_song', to: 'home#auto_complete_song'
  # get 'auto_complete_artist', to: 'home#auto_complete_artist'
  get 'auto_complete_word', to: 'home#auto_complete_word'

  #お問い合わせ
  get 'contact' => 'contact#index'
  post 'contact/thanks' => 'contact#thanks'
  get 'contact/unsubscribe' => 'contact#unsubscribe'

  resources :lists do #プレイリスト用
    put :sort
  end
  resources :charges #決済用
  # resources :person_infos, expect: [:show, :new, :edit] #個人情報
  
  resources :relationships, only: [:create, :destroy]   #フォロー、アンフォロー
  resources :favorites, only: [:create, :destroy]       #プレイリストお気に入り、解除 

  #ユーザー確認画面
  get "users/:id/playlist" => "users#playlist", as: 'users_playlist'
  get "users/:id/purchasehistory" => "users#purchasehistory", as: 'users_purchasehistory' #購入履歴
  get "users/:id/favuser" => "users#favuser", as: 'users_favuser'                         #お気に入りユーザー
  get "users/:id/favplaylist" => "users#favplaylist", as: 'users_favplaylist'             #お気に入りプレイリスト
  get "users/:id/salesmanage" => "users#salesmanage", as: 'users_salesmanage'             #売り上げ管理ページ
  get "users/:id/salesmonth" => "users#salesmonth", as: 'users_salesmonth'                #月間売り上げ管理ページ
  get "users/:id/payment" => "users#payment", as: 'users_payment'                         #決済設定
  #個人情報登録ページ
  get 'users/:id/person_info', to: 'person_info#index', as: 'person_info' 
  post 'users/:id/person_info', to: 'person_info#create'
  patch 'users/:id/person_info', to: 'person_info#update'
  put 'users/:id/person_info', to: 'person_info#update'
  #メール通知、ON/OFF
  get '/mail_notice', to: 'mail_notice#index', as: 'mail_notice' 
  patch 'mail_notice', to: 'mail_notice#update'
  put '/mail_notice', to: 'mail_notice#update'
  #プレイリスト公開設定
  get "users/:id/list_release" => "users#list_release", as: 'list_release'                

  #検索
  get 'searches/all_result'
  get 'searches/playlist'
  get 'searches/user'

  #　twitter連携　解除用
  delete 'disconnect', to: 'social_profile#destroy'
  
end

app/models/list.rb
class List < ApplicationRecord
  #paranoia 論理削除
  acts_as_paranoid
  
  ##Scope
  #公開状態かどうか
  scope :is_status, -> { where(status: "release") }
  
  ##Relation
  belongs_to :user, -> { unscope(where: :deleted_at) } #paranoia制約なし
  has_many :list_favorites, dependent: :destroy

  has_many :tracks, -> { unscope(where: :deleted_at) }, inverse_of: :list, dependent: :destroy #paranoia制約なし
  accepts_nested_attributes_for :tracks, reject_if: :all_blank, allow_destroy: true

  has_many :purchases, dependent: :destroy
  # has_many :users, through: :users

  #プレイリストお気に入り機能
  has_many :list_favorites, dependent: :destroy
  has_many :favorite_lists, through: :list_favorites, source: :user

  # #gem acts-as-taggable-on タグ機能
  acts_as_taggable
  

  ## Validation
  #ジャンルvalidate (日本語、英語、英数字、アンダーバーのみ)
  validates :tag_list, tag: true
  
  validates :title, presence: true, length: { maximum: 50 }, list_title: true
  validates :description, presence: true, length: { maximum: 3000 } 
  # validates :price, presence: true, numericality: true, :numericality => { :greater_than_or_equal_to => 100, :less_than_or_equal_to => 5000 }
  validates :price, presence: true, numericality: true
  validates_numericality_of :price,  greater_than_or_equal_to: 100
  validates_numericality_of :price,  less_than_or_equal_to: 5000
  
  #５曲以上入っているか確認　validation作業に入ったらコメント外す（削除済みの曲は除外）
  after_save do
    if self.tracks.without_deleted.count < 5
      self.errors.add(:base, "５曲以上登録してください。")
      raise ActiveRecord::Rollback
    end
  end
  
  #ムードは1個以上 30個まで
  before_save do
    if self.tag_list.count == 0
      self.errors.add(:base, "ムードは1つ以上入力してください。")
      raise ActiveRecord::Rollback
    end
    
    if self.tag_list.count > 30
      extra_tags = self.tag_list.count - 30
      self.tag_list.slice!(30, self.tag_list.count - 1) 
    end
  end
  
  #ムードは99文字まで
  before_save do
    self.tag_list.each_with_index do |val, i|
      if  self.tag_list[i].length > 99
        self.tag_list[i] = self.tag_list[i].slice(0, 98)
      end
    end
  end
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :gon_current_user, only: [:show]

  def show
    @list = List.with_deleted.find_by(id: params[:id])
    @display_list = true
    @user = @list.user
    if @list.nil?
      reject_page
    else
      if current_user != nil and @list.user == current_user
        @display_list = true
        if is_release_list?(@list) != true
          flash.now[:alert] = "このプレイリストは非公開です。<br>
                          <a id='listRelease' href='#{list_release_path(current_user)}'>プレイリストを公開する</a>".html_safe
        end
      else
        #非公開リストは行けないように
        if @list.status == "closed"
          reject_page
        end

        unless is_purchase?(current_user, @list) 
          if @list.paranoia_destroyed?
            reject_page
          else
            @display_list = false
          end
        end
        
      end
    end
    
    @customer = find_or_create_stripe_customer(current_user)
    
  end

  def new
    if current_user.nil?
      redirect_to new_user_session_path
      
    else
      #アカウント情報が登録済みかどうか
      if PersonInfo.where(user_id: current_user.id).empty?
        redirect_to person_info_path(current_user, ref: "list_add")
        
      else
        @list = List.new
        
      end
      
    end
    
  end

  def edit
    reject_pageh if current_user.nil?

    @list = current_user.lists.find_by(id: params[:id])
    
    if @list.nil? || @list.paranoia_destroyed?
      reject_page
      
    else
      if @tracks.nil?
        @tracks = @list.tracks.without_deleted.sort_by(&:row_order)
      end
      
    end

  end

  def create
    reject_pageh if current_user.nil?

    @list = current_user.lists.new(list_params)
    is_stripe = false #Stripe連携済みかのフラグ
    
    unless current_user.stripe_acct_id.nil? #Stripe連携済だったら
      @list.status = "release"
      is_stripe = true
    end
    
    if @list.save
      if is_stripe
        redirect_to users_playlist_path(current_user), notice: "「#{trun_str(@list.title, 18)}」を作成しました"
      else
        redirect_to users_payment_path(current_user)
      end
      
    else
      @tracks = @list.tracks
      render 'edit'
    end

  end

  def update
    reject_pageh if current_user.nil?

    @list = current_user.lists.find_by(id: params[:id])
    
    if !@list.nil?
      if @list.update(list_params)
        # 削除済みのトラックを物理削除する
        mylist_tracks = @list.tracks
        mylist_tracks.each_with_index do |track, i|
          unless mylist_tracks[i].deleted_at.nil?
            mylist_tracks[i].really_destroy!
          end
        end
        redirect_to users_playlist_path(current_user), notice: "「#{trun_str(@list.title, 18)}」を更新しました"
      else
        @tracks = @list.tracks.sort_by(&:row_order)
        render 'edit'
      end
    else
      redirect_to users_playlist_path(current_user), notice: "「#{trun_str(@list.title, 18)}」の更新に失敗しました"
    end

  end

  def destroy
    reject_pageh if current_user.nil?

    @list = current_user.lists.find_by(id: params[:id])
    
    if !@list.nil?
      @list.destroy
      redirect_to users_playlist_path(current_user), notice: "「#{trun_str(@list.title, 18)}」を削除しました"
    else
      redirect_to users_playlist_path(current_user), notice: "「#{trun_str(@list.title, 18)}」の削除に失敗しました"
    end

  end

  private

  def list_params
    params.require(:list).permit(:title, :description, :price, :tag_list, tracks_attributes:[:id, :artist, :song, :description, :recommend, :row_order, :_destroy])
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_fav_form.html.haml
-# プレイリストお気入り機能
%div{id: "favorite_change-#{list.id}", class: "favchange"}
  - if current_user.favorite?(list)
    = render "lists/unfavorite",list: list
  - else
    = render "lists/favorite",list: list

app/views/lists/_favorite.html.haml
= link_to favorites_path(list_id: list.id), method: :post, remote: true do
    = button_tag :type => "button", :class =>"btn btn__favorite__square" do
        %i.material-icons star
        お気に入り

app/views/lists/_icon_desc.html.haml
.l__iconDesc
  .icon__discription
    = link_to "", :class => 'modal-syncer js__listBack', "data-toggle" => "modal", 'data-target' => 'modal-iconDec' do
      %i.material-icons help_outline
      %span.iconHelp__title アイコンの説明

  %h4 曲名、アーティスト名は直接入力のため誤字脱字にお気をつけください。

  -# アイコンの説明モーダルウィンドウ
  .modal-content.modal__iconDesc{:id => "modal-iconDec"}
    -# モーダルウィンドウのコンテンツ開始
    .r__modalContent
    .l__iconDescCore.clearfix
      .iconDesc
        .iconDesc__left
          .l__icon
            %i.material-icons star_border
        .iconDesc__right
          %span.modal_title　お気に入り
          %span.modal_desc　プレイリストの中でも特にお気に入りの曲はこのアイコンを選択しましょう。

      .iconDesc
        .iconDesc__left
          .l__icon
            %i.material-icons delete_forever
        .iconDesc__right
          %span.modal_title　曲の削除
          %span.modal_desc　曲を削除することができます。

      .iconDesc
        .iconDesc__left
          .l__icon
            %i.material-icons dehaze
        .iconDesc__right
          %span.modal_title　並び替え
          %span.modal_desc　ドラッグまたはタップしながら曲を移動させることが出来ます。
        
    -# モーダルウィンドウのコンテンツ終了
    %p.text-center
      %a#modal-close.button-link 閉じる

app/views/lists/_list.html.haml
%ul.card
  - lists.each_with_index do |list, i|
    %li
      - if is_purchase?(current_user, list) 
        //purchased
        .l__upper
          .l__img
            = render 'users/is_image', user: list.user
          %span.listtitle= link_to trun_str(list.title, 21), list_path(list) , class: "testclass"
          %span.author= link_to trun_str(list.user.name, 23), users_playlist_path(list.user)
        .l__bottom
          %p= trun_str(list.description, 40)
          .tags
            - list.tag_list.each.with_index(0) do |listmood, i|
              - if i > 4
                %span.genretag･･･
                - break
              - else
                %span.genretag
                  = link_to trun_str(listmood, 30), chart_path(mood: listmood, sort: Constants::SORT)
            .l__footerPrice
              //playlist favorite
              %span.favoriteStar
                %i.material-icons star_rate
                = list.list_favorites.count
              %span.label.label-warning 購入済み
              %span.listprice ¥#{list.price}
      
      - else
        //not purchased
        = link_to list_path(list) do
          .l__upper
            .l__img
              = render 'users/is_image', user: list.user

            -if is_signin && is_signed(current_user.id, list.user.id)
              - if !is_release_list?(list)
                %span.liststatus 非公開
            %span.listtitle= trun_str(list.title, 21)
            %span.author= trun_str(list.user.name, 23)
          .l__bottom
            %p= trun_str(list.description, 40)
            .tags
              - list.tag_list.each.with_index(0) do |listmood, i|
                - if i > 4
                  %span.genretag･･･
                  - break
                - else
                  %span.genretag
                    = trun_str(listmood, 30)
            .l__footerPrice
              %span.favoriteStar
                %i.material-icons star_rate
                = list.list_favorites.count
              -if is_signin && is_signed(current_user.id, list.user.id)
                %span.label.label-default My Playlist
              %span.listprice ¥#{list.price}

app/views/lists/_track_fields.html.haml
.track_item.l__tracks
  %table
    %tbody
      %tr
        %td
          = f.input :recommend, label: ".", as: :boolean, boolean_style: :inline, label_html: { id: "custom-checkbox#{f.index}", class: 'track_recommend' }, input_html: { id: "custom-checkbox#{f.index}", class: "custom-check-box" }
        %td.track_no
        %td.other
          %span.trackSong= f.text_field :song, placeholder: "曲名", class: "auto_word"
          %span.trackArtist= f.text_field :artist, placeholder: "アーティスト名", class: "auto_word"
          %span#description= f.text_area :description, placeholder: "曲の説明（1000文字まで）", input_html: {rows: 2}
        %td
          %span.track_delete
            = link_to_remove_association f, { wrapper_class: 'track_item' } do
              %i.material-icons.still delete_forever
        %td
          %span.track_sorticon
            %i.material-icons.still dehaze
        %td
          %span.sort_no= f.hidden_field :row_order, class: 'sort_order'



    

app/views/lists/_unfavorite.html.haml
= link_to favorite_path(current_user, list_id: list.id), method: :delete, remote: true do
    = button_tag :type => "button", :class =>"btn unfavorite btn__favorite__square" do
        %i.material-icons star
        お気に入り

app/views/lists/edit.html.haml
- set_meta_tags title: "プレイリストの編集"

- if @list.errors.any?
  #error_explanation.alert.alert-danger
    %ul
      - @list.errors.full_messages.each do |message|
        %li= message

.l__listShow.l__listEdit
  = simple_form_for @list do |f|
    .l__playlist
      .l__playlistCore.clearfix
          
        .playlist__text
          .playlist__title
            = f.input :title, label: "プレイリスト名", placeholder: 'プレイリスト名（必須５０文字まで）'
          .list_mood
            = f.label :playlist_mood do
              ムード
              %span.form-require 必須
            - if f.object.tag_list.empty?
              - delimiter_char = ''
            -else
              - delimiter_char = '# '
            = f.text_field :tag_list, value: delimiter_char + f.object.tag_list.to_s, label: false, placeholder: '気分（#ワークアウト #チル #ドライブ...）', input_html: {rows: 1}
          .span.playlist__price
            = f.label :price do
              価格
              %span.form-require 必須
            .price-input
              ￥
              = f.input :price, label: false, required: false, error: false, placeholder: '例）100', as: :string
              
      .span.playlist__discription
        = f.label :description do
          プレイリスト説明
          %span.form-require 必須
        = f.input :description, label: false, placeholder: 'プレイリストの説明（3000文字以内）', :input_html => {:rows => 5}

    = render partial: 'icon_desc'

    #track_section.table-sortable
      = f.fields_for :tracks, @tracks do |track|
        - if track.object.deleted_at.nil?
          = render 'track_fields', f: track

    .field_track_add
      = link_to_add_association '曲を追加する', f, :tracks,:"data-association-insertion-node" => "#track_section",:"data-association-insertion-method" => "append"
    .actions
      - if @list.id == nil
        = f.submit "作成"
      - else
        = f.submit "更新"
        = link_to "削除", @list, method: :delete, data: { confirm: "#{@list.title}を削除してもよろしいですか?\n既に購入したユーザーは削除後も閲覧することができます。" }
    
    

    

app/views/lists/new.html.haml
- set_meta_tags title: "プレイリストの新規作成"

- if @list.errors.any?
  #error_explanation.alert.alert-danger
    %ul
      - @list.errors.full_messages.each do |message|
        %li= message

.l__listShow.l__listEdit
  = simple_form_for @list do |f|
    .l__playlist
      .l__playlistCore.clearfix
          
        .playlist__text
          .playlist__title
            = f.input :title, label: "プレイリスト名", placeholder: 'プレイリスト名（必須５０文字まで）'
          .list_mood
            = f.label :playlist_mood do
              ムード
              %span.form-require 必須
            = f.text_field :tag_list, value: f.object.tag_list.to_s, placeholder: '気分（#ワークアウト #チル #ドライブ...）'
          .span.playlist__price
            = f.label :price do
              価格
              %span.form-require 必須
            .price-input
              ￥
              = f.input :price, label: false, required: false, error: false, placeholder: '例）100', as: :string
              
      .span.playlist__discription
        = f.label :description do
          プレイリスト説明
          %span.form-require 必須
        = f.input :description, label: false, placeholder: 'プレイリストの説明（3000文字以内）', :input_html => {:rows => 5}
    
    = render partial: 'icon_desc'

    #track_section.table-sortable
      = f.fields_for :tracks, @list.tracks.sort_by(&:row_order) do |track|
        = render 'track_fields', f: track
          
    .field_track_add
      = link_to_add_association '曲追加', f, :tracks,:"data-association-insertion-node" => "#track_section",:"data-association-insertion-method" => "append"

    .actions
      = f.submit "作成"
      

app/views/lists/show.html.haml
- if @user.user_profile.avatar.file.nil?
  - set_meta_tags og:{ title: @list.title, description: @list.description, image: image_url("/default/thumb_noavatar.jpg") } 
- else
  - set_meta_tags og:{ title: @list.title, description: @list.description, image: image_url(@user.user_profile.avatar.thumb.to_s ) } 




// 購入ボタンのモーダルウィンドウ　紐づけ用
- i = 1

.l__listShow.l__s
  .l__playlist
    -if is_signin && is_signed(current_user.id, @list.user.id)
      .playlist__editLink
        = link_to edit_list_path(@list), { class: "edit_link" } do
          = button_tag :type => "button", :class =>"btn btn__favorite__square" do
            %i.material-icons edit
            プレイリストを編集
            
      -if !is_release_list?(@list)
        %span.liststatus 非公開
      
    .l__playlistCore.clearfix
      .playlist__topimg
        .l__img
          = render 'users/is_image', user: @user
        .span.trackCount #{@list.tracks.count}曲
      
      .playlist__text
        .playlist__title
          - if @list.paranoia_destroyed?
            = @list.title + Constants::DLETE_MARK_LIST
          - else
            = @list.title
        
        .playlist__author
          - if @list.user.paranoia_destroyed?
            #{@list.user.name + Constants::DLETE_MARK_USER}
          - else
            = link_to @list.user.name, users_playlist_path(@list.user)
            // 本人確認バッジ
            - if is_identity?(@list.user)
              = render "users/identity"
            
        -unless @list.paranoia_destroyed?
          - if @display_list == true
            -unless is_signin && is_signed(current_user.id, @list.user.id)
              = render 'lists/fav_form', list: @list 
          - elsif is_release_list?(@list)
            = form_tag charges_path do
              .l__btn__purchase
                %label.amount
                .datafield
                  = hidden_field_tag :list, @list.id
                  
                // 購入前のログイン判定用
                %button.btn__purchase.buy_btn{type: "button"} 購入する
              
              // Stripe決済部分
              .hide_checkout
                - if @customer.nil?
                  %script.stripe-button{"data-amount" => "#{@list.price}",
                    "data-description" => "#{@list.title}",
                    "data-email" => "",
                    "data-key" => "#{Rails.configuration.stripe[:publishable_key]}",
                    "data-label" => "購入",
                    "data-locale" => "auto",
                    "data-currency" => "jpy",
                    "data-name" => "StarListz",
                    "data-panel-label" => "プレイリストを購入",
                    :src => "https://checkout.stripe.com/checkout.js"}
                - else
                  %script.stripe-button{"data-amount" => "#{@list.price}",
                    "data-description" => "#{@list.title}",
                    "data-email" => "#{@customer.email}",
                    "data-key" => "#{Rails.configuration.stripe[:publishable_key]}",
                    "data-label" => "購入",
                    "data-locale" => "auto",
                    "data-currency" => "jpy",
                    "data-name" => "StarListz",
                    "data-panel-label" => "プレイリストを購入",
                    :src => "https://checkout.stripe.com/checkout.js"}

          .span.playlist__price ￥#{@list.price}
    -if @list.description.length >= 140
      -if @list.description.try(:split, "\n").nil?
        .span.playlist__discription
          .grad-wrap
            %input#trigger1.grad-trigger{:type => "checkbox"}/
            %label.grad-btn{:for => "trigger1"}
              %i.material-icons keyboard_arrow_down
            .grad-item
              = text_url_to_link(@list.description).html_safe
      -else
        .span.playlist__discription
          .grad-wrap
            %input#trigger1.grad-trigger{:type => "checkbox"}/
            %label.grad-btn{:for => "trigger1"}
              %i.material-icons keyboard_arrow_down
            .grad-item
              = text_url_to_link(safe_join(@list.description.split("\n"), tag(:br))).html_safe

    -else
      -if @list.description.try(:split, "\n").nil?
        .span.playlist__discription= text_url_to_link(@list.description).html_safe
      -else
        .span.playlist__discription= text_url_to_link(safe_join(@list.description.split("\n"), tag(:br))).html_safe
      
    
    
    .span
      - @list.tag_list.each.with_index(0) do |listmood, i|
        %span.genretag
          = link_to listmood, chart_path(mood: listmood, sort: Constants::SORT)
  
  - if @display_list == true
    .track_section
      #cont_desc_show.l__tracks
        %table
          %tbody
            %tr
              %td
                %span.favoriteStar
                  おすすめ
              %td.track_no_sample
              %td
                %span.trackSong 曲名
                %span.trackArtist アーティスト名
              %td
                %span.trackComment
                  曲への気持ち
                  

      - @list.tracks.sort_by(&:row_order).each_with_index do |track, i|
        .l__tracks
          %table
            %tbody
              %tr
                %td
                  - if track.recommend == true
                    %span.favoriteStar
                      %i.material-icons star_rate
                %td.track_no
                %td
                  %span.trackSong= track.song
                  %span.trackArtist= track.artist
                %td
                  - if track.description != nil && track.description.length > 0
                    %a.modal-syncer.js__listBack.trackComment{"data-target" => "modal-content-#{i}"} 
                      %img{:src => "#{asset_path "chat.png"}", :width => "24", :height => "24"} 


        .modal-content.modal__comment{:id => "modal-content-#{i}"}
          // モーダルウィンドウのコンテンツ開始
          .r__modalContent
          .l__playlistCore.clearfix
            .playlist__img
              .l__img
                = render 'users/is_image', user: @user
            .playlist__text
              %span.modal_song= track.song
              %span.modal_artist= track.artist
          %hr
          .playlist__song_description
            -if track.description.try(:split, "\n").nil?
              %p= text_url_to_link(track.description).html_safe
            -else
              %p= text_url_to_link(safe_join(track.description.split("\n"), tag(:br))).html_safe

          #tool-btn.clear
            %a.clipbtn.btn1{:href => "#"} 
              %i.material-icons
                file_copy
              曲名、アーティスト名をコピー
            %a.btn2{href: "#{"https://www.youtube.com/results?search_query=" + track.artist + " " + track.song}", target: "_blank"}
              %span
                %img{:src => "/images/yt_icon_rgb.png"}
              曲をYouTubeで検索

          // モーダルウィンドウのコンテンツ終了
          %p.text-center
            %a#modal-close.button-link 閉じる

- if @display_list == true && !is_signed(current_user.id, @list.user.id)
  .it-Footer_social
    .SocialMediaShareButton.SocialMediaShareButton--twitter{:role => "button", :style => "margin-right: 0px; margin-top: 0px;", :tabindex => "0"}
      %div{:style => "width: 32px; height: 32px;"}
        %svg.social-icon.social-icon--twitter{:fill => "white", :height => "32", :viewbox => "0 0 64 64", :width => "32"}
          %g
            %circle{:cx => "32", :cy => "32", :fill => "#00aced", :r => "31"}
          %g
            %path{:d => "M48,22.1c-1.2,0.5-2.4,0.9-3.8,1c1.4-0.8,2.4-2.1,2.9-3.6c-1.3,0.8-2.7,1.3-4.2,1.6 C41.7,19.8,40,19,38.2,19c-3.6,0-6.6,2.9-6.6,6.6c0,0.5,0.1,1,0.2,1.5c-5.5-0.3-10.3-2.9-13.5-6.9c-0.6,1-0.9,2.1-0.9,3.3 c0,2.3,1.2,4.3,2.9,5.5c-1.1,0-2.1-0.3-3-0.8c0,0,0,0.1,0,0.1c0,3.2,2.3,5.8,5.3,6.4c-0.6,0.1-1.1,0.2-1.7,0.2c-0.4,0-0.8,0-1.2-0.1 c0.8,2.6,3.3,4.5,6.1,4.6c-2.2,1.8-5.1,2.8-8.2,2.8c-0.5,0-1.1,0-1.6-0.1c2.9,1.9,6.4,2.9,10.1,2.9c12.1,0,18.7-10,18.7-18.7 c0-0.3,0-0.6,0-0.8C46,24.5,47.1,23.4,48,22.1z"}

    .SocialMediaShareButton.SocialMediaShareButton--facebook{:role => "button", :style => "margin-right: 30px; margin-top: 0px;", :tabindex => "0"}
      %div{:style => "width: 32px; height: 32px;"}
        %svg.social-icon.social-icon--facebook{:fill => "white", :height => "32", :viewbox => "0 0 64 64", :width => "32"}
          %g
            %circle{:cx => "32", :cy => "32", :fill => "#3b5998", :r => "31"}
          %g
            %path{:d => "M34.1,47V33.3h4.6l0.7-5.3h-5.3v-3.4c0-1.5,0.4-2.6,2.6-2.6l2.8,0v-4.8c-0.5-0.1-2.2-0.2-4.1-0.2 c-4.1,0-6.9,2.5-6.9,7V28H24v5.3h4.6V47H34.1z"}
      