config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks", :registrations => "users/registrations", :confirmations => "users/confirmations"}

  root 'home#index'
  get 'welcome' , to: 'home#welcome' #サンプルプレイリスト
  get 'samplelist' , to: 'home#samplelist' #サンプルプレイリスト
  # get 'name_check', to: 'home#name_check'#ユーザー名重複チェック用
  get 'chart' , to: 'home#chart' #チャート
  get 'about' , to: 'home#about' #プレイリストについて
  get 'privacy' , to: 'home#privacy' #個人情報保護
  get 'term' , to: 'home#term' #利用規約
  get 'tokutei' , to: 'home#tokutei' #特定商取引に関する表記
  #著作権どうするか
  # get 'copyright' , to: 'home#copyright'

  # get 'auto_complete_song', to: 'home#auto_complete_song'
  # get 'auto_complete_artist', to: 'home#auto_complete_artist'
  get 'auto_complete_word', to: 'home#auto_complete_word'

  #お問い合わせ
  get 'contact' => 'contact#index'
  post 'contact/thanks' => 'contact#thanks'
  get 'contact/unsubscribe' => 'contact#unsubscribe'

  resources :lists do #プレイリスト用
    put :sort
  end
  resources :charges #決済用
  # resources :person_infos, expect: [:show, :new, :edit] #個人情報
  
  resources :relationships, only: [:create, :destroy]   #フォロー、アンフォロー
  resources :favorites, only: [:create, :destroy]       #プレイリストお気に入り、解除 

  #ユーザー確認画面
  get "users/:id/playlist" => "users#playlist", as: 'users_playlist'
  get "users/:id/purchasehistory" => "users#purchasehistory", as: 'users_purchasehistory' #購入履歴
  get "users/:id/favuser" => "users#favuser", as: 'users_favuser'                         #お気に入りユーザー
  get "users/:id/favplaylist" => "users#favplaylist", as: 'users_favplaylist'             #お気に入りプレイリスト
  get "users/:id/salesmanage" => "users#salesmanage", as: 'users_salesmanage'             #売り上げ管理ページ
  get "users/:id/salesmonth" => "users#salesmonth", as: 'users_salesmonth'                #月間売り上げ管理ページ
  get "users/:id/payment" => "users#payment", as: 'users_payment'                         #決済設定
  #個人情報登録ページ
  get 'users/:id/person_info', to: 'person_info#index', as: 'person_info' 
  post 'users/:id/person_info', to: 'person_info#create'
  patch 'users/:id/person_info', to: 'person_info#update'
  put 'users/:id/person_info', to: 'person_info#update'
  #メール通知、ON/OFF
  get '/mail_notice', to: 'mail_notice#index', as: 'mail_notice' 
  patch 'mail_notice', to: 'mail_notice#update'
  put '/mail_notice', to: 'mail_notice#update'
  #プレイリスト公開設定
  get "users/:id/list_release" => "users#list_release", as: 'list_release'                

  #検索
  get 'searches/all_result'
  get 'searches/playlist'
  get 'searches/user'

  #　twitter連携　解除用
  delete 'disconnect', to: 'social_profile#destroy'
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :gon_current_user, only: [:playlist, :user]
  
  def all_result
  end
  
  def playlist
  end

  def user
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search_header.html.haml
.bg__w
    .l__searchform
        = search_form_for  @q, html: {class: 'navbar-form' }, url: searches_all_result_path, enforce_utf8: false do |f|
            = text_field_tag :q, @search_word, placeholder: "キーワード", class: "search-box"
            = button_tag "#{content_tag(:i, '', class: 'glyphicon glyphicon-search')}".html_safe, type: :submit, class: 'btn search-btn'

    %ul.l__search__tab
        %li{ class: controller.action_name == 'all_result' ? 'active' : '' }
            = link_to "検索結果", :controller => "searches", :action => "all_result", q: params[:q]
        %li{ class: controller.action_name == 'playlist' ? 'active' : '' }
            = link_to "プレイリスト", :controller => "searches", :action => "playlist", q: params[:q]
        %li{ class: controller.action_name == 'user' ? 'active' : '' }
            = link_to "ユーザー", :controller => "searches", :action => "user", q: params[:q]

app/views/searches/all_result.html.haml
- set_meta_tags title: "検索結果"

= render :partial => "searches/search_header"


.l__search__tab__box
    %h2 ユーザー
    - if @search_user != nil and not @search_user.empty?
        = render "users/user", users: @user_pages.limit(3)
        
    = link_to "すべて見る", { :controller => "searches", :action => "user", q: params[:q] }, class: "link"
    
    %h2 プレイリスト
    - if @search_list != nil and not @search_list.empty?
        = render "lists/list", lists: @list_pages.limit(3), customer: @customer
        
    = link_to "すべて見る", { :controller => "searches", :action => "playlist", q: params[:q] }, class: "link"

app/views/searches/playlist.html.haml
= render :partial => "searches/search_header"

.l__search__tab__box
  - if @search_list != nil and not @search_list.empty?
    = render "lists/list", lists: @list_pages, customer: @customer
  -if @list_pages != nil
    #list_paginator
      = paginate @list_pages, param_name: 'list_page'

app/views/searches/user.html.haml
= render :partial => "searches/search_header"

.l__search__tab__box
  - if @search_user != nil and not @search_user.empty?
    = render "users/user", users: @user_pages
  -if @user_pages != nil
    #user_paginator
      = paginate @user_pages, param_name: 'user_page'