config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks", :registrations => "users/registrations", :confirmations => "users/confirmations"}

  root 'home#index'
  get 'welcome' , to: 'home#welcome' #サンプルプレイリスト
  get 'samplelist' , to: 'home#samplelist' #サンプルプレイリスト
  # get 'name_check', to: 'home#name_check'#ユーザー名重複チェック用
  get 'chart' , to: 'home#chart' #チャート
  get 'about' , to: 'home#about' #プレイリストについて
  get 'privacy' , to: 'home#privacy' #個人情報保護
  get 'term' , to: 'home#term' #利用規約
  get 'tokutei' , to: 'home#tokutei' #特定商取引に関する表記
  #著作権どうするか
  # get 'copyright' , to: 'home#copyright'

  # get 'auto_complete_song', to: 'home#auto_complete_song'
  # get 'auto_complete_artist', to: 'home#auto_complete_artist'
  get 'auto_complete_word', to: 'home#auto_complete_word'

  #お問い合わせ
  get 'contact' => 'contact#index'
  post 'contact/thanks' => 'contact#thanks'
  get 'contact/unsubscribe' => 'contact#unsubscribe'

  resources :lists do #プレイリスト用
    put :sort
  end
  resources :charges #決済用
  # resources :person_infos, expect: [:show, :new, :edit] #個人情報
  
  resources :relationships, only: [:create, :destroy]   #フォロー、アンフォロー
  resources :favorites, only: [:create, :destroy]       #プレイリストお気に入り、解除 

  #ユーザー確認画面
  get "users/:id/playlist" => "users#playlist", as: 'users_playlist'
  get "users/:id/purchasehistory" => "users#purchasehistory", as: 'users_purchasehistory' #購入履歴
  get "users/:id/favuser" => "users#favuser", as: 'users_favuser'                         #お気に入りユーザー
  get "users/:id/favplaylist" => "users#favplaylist", as: 'users_favplaylist'             #お気に入りプレイリスト
  get "users/:id/salesmanage" => "users#salesmanage", as: 'users_salesmanage'             #売り上げ管理ページ
  get "users/:id/salesmonth" => "users#salesmonth", as: 'users_salesmonth'                #月間売り上げ管理ページ
  get "users/:id/payment" => "users#payment", as: 'users_payment'                         #決済設定
  #個人情報登録ページ
  get 'users/:id/person_info', to: 'person_info#index', as: 'person_info' 
  post 'users/:id/person_info', to: 'person_info#create'
  patch 'users/:id/person_info', to: 'person_info#update'
  put 'users/:id/person_info', to: 'person_info#update'
  #メール通知、ON/OFF
  get '/mail_notice', to: 'mail_notice#index', as: 'mail_notice' 
  patch 'mail_notice', to: 'mail_notice#update'
  put '/mail_notice', to: 'mail_notice#update'
  #プレイリスト公開設定
  get "users/:id/list_release" => "users#list_release", as: 'list_release'                

  #検索
  get 'searches/all_result'
  get 'searches/playlist'
  get 'searches/user'

  #　twitter連携　解除用
  delete 'disconnect', to: 'social_profile#destroy'
  
end

app/models/contact.rb
class Contact < ApplicationRecord

  # attr_accessor :name, :email, :message

  # validates :name, :presence => {:message => '名前を入力してください'}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}, format: { with: VALID_EMAIL_REGEX ,:message => 'メールアドレスを入力してください'}
  validates :title, :presence => {:message => '件名を入力してください'}
  validates :message, :presence => {:message => '詳細を入力してください'}
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @contact = Contact.new
    render :action => 'index'
  end

  def thanks
    begin
      @contact = Contact.new(contact_params)
      if verify_recaptcha(model: @contact) && @contact.valid?
        ContactMailer.received_email(@contact, current_user).deliver
        redirect_to root_path, notice: "お問い合わせを送信しました"
        log_supportContact(@contact, current_user)

      else
        render 'index'

      end

    rescue StandardError => e
      log_error(e, Constants::LOG_Fatal_LEVEL, "ContactController : StandardError")
      flash.now[:alert] = "お問い合わせの送信に失敗しました"
      render "index"
    end
  end
  
  def unsubscribe
    if current_user.nil?
      reject_page
    else
      @contact = Contact.new
    end
  end

  private

  def contact_params
    # submitしたデータのうち、Model作成に必要なものを
    # permitの引数に指定する
    params.require(:contact).permit(:name, :email, :title, :message)
  end


end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/index.html.haml
- set_meta_tags title: "お問い合わせ"

.l__contact
  .form__contact
    %h2 お問い合わせ
    = simple_form_for @contact, :url => contact_thanks_path  do |f|
      - if @contact.errors.any?
        %strong 入力内容にエラーがあります
        %ul
          - @contact.errors.each do |attr, msg|
            %li= msg
      = f.input :name, label: "名前", error: false, as: :string
      = f.input :email, label: "メールアドレス", error: false, as: :string
      = f.input :title, label: "件名", error: false, as: :string
      = f.input :message, label: "詳細", error: false, input_html: {rows: 6}
      
      = recaptcha_tags
      
      = f.submit '送信'
      
  %p
    - if is_signin
      = link_to "退会はこちら", contact_unsubscribe_path

app/views/contact/unsubscribe.html.haml
.l__contact.l__unsubscribe

  = image_tag asset_path "Logo.png"
  %h2 StarListzを退会しますか？
  %p ※退会処理後にアカウント、プレイリストのデータを元に戻すことはできません。
  %p ※Stripeのアカウントは削除されません。
  

  .form__contact
    = simple_form_for @contact, :url => registration_path(current_user), method: :delete do |f|
      = f.input :message, label: "退会理由", error: false, input_html: {rows: 6}, placeholder: '退会理由を入力してください'
      = f.submit '退会', data: { confirm: "退会します。よろしいですか？" }